### ISSUE TITLE
Deleting of nodes/devices/... happens without confirmation ("are you sure") nor with undo

### ISSUE THREAD

**Issue by aaronkaplan** [FunkFeuer/Graz#11]
If a user accidentally clicks "delete" (trash can icon), the object is deleted without confirmation.
Please add a confirmation and /or undo functionality.

**Comment by tanzer** [comment]
The commits
- https://github.com/FunkFeuer/common-node-db/commit/ad06a37fac5f2f8cf8b37eff70133d7dc1367929
- https://github.com/Tapyr/tapyr/commit/6f29814e633af83a025bb1f9afbead17dad53e0d

implement undo for delete.

**Comment by aaronkaplan** [comment]
Seems not to work for nodedb-staging.ffgraz.net: POST /Admin/FFG/Node/undo -> response: forbidden.
(user Juergen). Probably a permission problem.

**Comment by tanzer** [comment]
The permission problem was fixed with commit: https://github.com/FunkFeuer/common-node-db/commit/b4e7b925880a175e5f6c8dacc333ca9b1bb50fda
