### ISSUE TITLE
dashboard: CSS style - yellow/red is confusing

### ISSUE THREAD

**Issue by aaronkaplan** [FunkFeuer/Graz#13]
In the detailed edit view, the yellow textbox with red letters looks like there is some problem in a field. 
That's confusing. Please mark the current focus of editing differently (like for example github does - very thin light blue border - or similar). 
Please inspect current common best practices with UI design for this.

**Comment by tanzer** [comment]
I fixed this in tapyr commit 409198465e20 and updated nodedb-graz-tmp.funkfeuer.at and nodedb.ffgraz.net.

**Comment by aaronkaplan** [comment]
New (connected?) Problem:
try to create a new node, add a person as manager, try to close the pop-up box. Does not work!

**Comment by tanzer** [comment]
The manager pop-up box can only be used to select an existing person (or company,...). For the Graz node-db, If you enter 'li' into the field `Nachname`, you should get a list of several persons; if you select any of those, you can use the apply button to close the pop-up and enter the person into the manager field. 
You should always be able to close the pop-up with the close button.
Is that the behaviour you see?

**Comment by aaronkaplan** [comment]
closing this issue now, since the problem with the pop-up box not closing is actually a separate issue. Made a new one for that: #37.
