### ISSUE TITLE
Password Recovery doesn't show confirmation

### ISSUE THREAD

**Issue by equinox0815** [FunkFeuer/Graz#39]
When a user requests a password recovery the mail gets sent but the Web UI doesn't present a confirmation but just shows the login form again.

**Comment by tanzer** [comment]
This is fixed by the commits:
https://github.com/Tapyr/tapyr/commit/44813caf41e030f020520d49a7cf5665e4c02ee5
https://github.com/FunkFeuer/common-node-db/commit/9e7019044d69956be282b9f5e215f73271bc7cb1
