### ISSUE TITLE
Email field too short

### ISSUE THREAD

**Issue by nicoonoclaste** [FunkFeuer/Graz#40]
The email field (during login) is restricted to 30 characters (on the client side).
This is too short.

**Comment by nicoonoclaste** [comment]
PS: Issue is with the HTML, not the DB itself

**Comment by tanzer** [comment]
Fixed in commit https://github.com/Tapyr/tapyr/commit/36b49ad1d2bb9a8fbbc4bee3bf787c7f2ecbdaa9
