### ISSUE TITLE
create new interface -> Netzwerkgerät yellow pop-up does not dissapear

### ISSUE THREAD

**Issue by aaronkaplan** [FunkFeuer/Graz#7]
seems like a browser problem? 
tested with 41.0.2272.76 (Developer Build) Ubuntu 14.04

cross-tested with Mac OS X , Chrome 41.0.2272.89 (64-bit), could not reproduce
Not reproducible in Firefox Ubuntu.

**Comment by tanzer** [comment]
Fixed in commit https://github.com/Tapyr/tapyr/commit/67fb1ac3d908bcdf6dc28de7da6ce98dd3223bf4
