### ISSUE TITLE
Dashboard: change "eye" icon to "filter" icon

### ISSUE THREAD

**Issue by aaronkaplan** [FunkFeuer/Graz#9]
- We would like to have a "filter" icon instead of the eye icon. This seems to be more intuitive.
- Also please change the behaviour that if you click on a row, then that row (and it's children (node -> devices -> interfaces)) get selected.

**Comment by equinox0815** [comment]
The current function of the eye is not really a filter but a select. I would prefer to have the complete table row as a 'button' for this and remove the eye button entirely.
A filter would be something different and would be a nice to have later. Anyway i don't think it is needed for the first release.

**Comment by tanzer** [comment]
Fixed by https://github.com/FunkFeuer/common-node-db/commit/3e013c816bb3b21abd1ac23d979c33cb7582d69f
